wordpress:
  image: wordpress:fpm
  working_dir: /var/www/html
  links:
    - db:mysql
  env_file:
    - "./docker/wordpress/wordpress.env"
  volumes:
    - "./wordpress/wp-content/:/var/www/html/wp-content"

db:
  image: mariadb
  env_file:
    - "./docker/db/db.env"
  volumes:
#    - "./docker/db/import:/docker-entrypoint-initdb.d/"
    - "./docker/db/config:/etc/mysql/conf.d"
  volumes_from:
    - luposraudonos_db_vol

web_server:
  build: "./docker/nginx"
  links:
    - wordpress
  volumes_from:
    - wordpress
  enviroment:
    - VIRTUAL_HOST=luposraudonos.lt
